[package]
name = "fsteszt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3"
memmap = "0.7"
rand = "0.8"

[profile.release]
strip = true
