[package]
name = "hdd-speed-test"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5"
memmap = "0.7"
rand = "0.8"
libc = "0.2"

[profile.release]
strip = true
